export const CARDS = [
  {
    CardTitle: "Card1",
    CardDescription: "Some card description of card 1",
    CardBackgroundUrl: "./src/assets/img.png",
    CardDate: "",
    CardAvailable: true,
    CardCountry: "USA",
  },
  {
    CardTitle: "Card2",
    CardDescription: "Some card description of card 2",
    CardBackgroundUrl: "./src/assets/img.png",
    CardDate: "",
    CardAvailable: false,
    CardCountry: "USA",
  },
  {
    CardTitle: "Card3",
    CardDescription: "Some card description of card 3",
    CardBackgroundUrl: "./src/assets/img.png",
    CardDate: "",
    CardAvailable: true,
    CardCountry: "USA",
  },
  {
    CardTitle: "Card4",
    CardDescription: "Some card description of card 4",
    CardBackgroundUrl: "./src/assets/img.png",
    CardDate: "",
    CardAvailable: true,
    CardCountry: "USA",
  },
  {
    CardTitle: "Card5",
    CardDescription: "Some card description of card 5",
    CardBackgroundUrl: "./src/assets/img.png",
    CardDate: "",
    CardAvailable: true,
    CardCountry: "USA",
  },
  {
    CardTitle: "Card6",
    CardDescription: "Some card description of card 6",
    CardBackgroundUrl: "./src/assets/img.png",
    CardDate: "",
    CardAvailable: true,
    CardCountry: "USA",
  },
];
